### ISSUE TITLE
Break out almost-equal into its own library?

### ISSUE THREAD

**Issue by ashaffer** [micro-js/scroll-to#1]
@queckezz Hey man, nice work! I was just about to make one of these myself.

Your almost-equal function I think is probably useful for lots of things though too. So it might be cool as its own module?

**Comment by queckezz** [comment]
Thanks, was pretty simple with `@f/animate`!

Done. b697a14a3f6bc90ff92d59255665d670d75b27f6

Also planning to create `scroll-to-element` and `scroll-into-view`.

**Comment by ashaffer** [comment]
Nice. Scroll-to-element and scroll-into-view will be great.
